services:
  cloudflare-s2s:
    image: cloudflared-s2s:staging
    #image: bastelbaus/cloudflared-s2s:latest    
    pull_policy: build
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    #build:
    #  context: .

    ports: # host_port : docker_port
      - 15650:15650 # the WebUI
      - 15651:15651 # the REST API
      - 51820:51820 # wireguard to test !

    volumes:
      - ./app:/var/app2
    #volumes:
    #  - ./app:/app # mounting local app directory
    #  - ~/cloudflared-mgr:/source
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

    #  - PUID=1000 # change this to your user id
    #  - PGID=1000 # change this to your group id
    #  - STORAGE_SECRET="change-this-to-yor-own-private-secret"

    # some additonal settings needed for routing
    #network_mode: "host"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
#      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      default:        
      macvlan_network:
        ipv4_address: ${ROUTER_IP}

networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
       - subnet: ${SUBNET}
#         ip_range: 192.168.1.23/32
         gateway: ${GATEWAY_IP}




#    networks:
#      control_network:
#          ipv4_address: 192.168.8.22
#      wireguard_bridge:


#networks:
#  control_network:
#    driver: bridge
#    driver_opts:
#<<<<<<< HEAD
#       com.docker.network.bridge.host_binding_ipv4: "192.168.8.23"
#       com.docker.network.bridge.gateway_mode_ipv4: "routed"
#       docker.network.bridge.name: control_network
#=======
#       com.docker.network.bridge.host_binding_ipv4: "192.168.9.2"
#       com.docker.network.bridge.gateway_mode_ipv4: "routed"
#      # com.docker.network.bridge.name: control_network
#>>>>>>> e93704896bce0f333c2cd71e04b5fd9a3d83fddd
#    ipam:
#      config:
#        - subnet: "192.168.8.0/23"
#          gateway: "192.168.9.1"
#          ip_range: "192.168.8.0/23"
#  wireguard_bridge:
#    driver: bridge
#<<<<<<< HEAD
 #   driver_opts:
 #     docker.network.bridge.name: wgb
 ##     com.docker.network.bridge.gateway_mode_ipv4: "routed"
 #     #com.docker.network.bridge.inhibit_ipv4: true
 #   ipam:
 #     config:
 #       - subnet: "192.168.1.0/24"
 #         gateway: "192.168.1.1"
#=======
#    driver_opts:
#      com.docker.network.bridge.name: wgb
#      com.docker.network.bridge.inhibit_ipv4: "true"
#    ipam:
#      config:
#        - subnet: "192.168.22.0/24"
#          gateway: "192.168.22.1"
#>>>>>> e93704896bce0f333c2cd71e04b5fd9a3d83fddd


#    networks:
#      macvlan:
#        ipv4_address: 192.168.10.17

#networks:
#  macvlan:
#    name: macvlan
#    driver: bridge
#    #driver: macvlan
#    driver_opts:
#      parent: eth0
#    ipam:
#      config:
#      - subnet: "192.168.10.0/24"
#        gateway: "192.168.10.1"

#        ip_range: "192.168.1.60/28"
