services:
  cloudflare-s2s:
    image: cloudflared-s2s:staging
    #image: bastelbaus/cloudflared-s2s:latest    
    pull_policy: build
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    #build:
    #  context: .

    ports: # host_port : docker_port
      - 15650:15650 # the WebUI
      - 15651:15651 # the REST API
      - 51820:51820 # wireguard to test !

    volumes:
      - ./app:/var/app2
    #volumes:
    #  - ./app:/app # mounting local app directory
    #  - ~/cloudflared-mgr:/source
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

    #  - PUID=1000 # change this to your user id
    #  - PGID=1000 # change this to your group id
    #  - STORAGE_SECRET="change-this-to-yor-own-private-secret"

    # some additonal settings needed for routing
    #network_mode: "host"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
#      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      default:        
      macvlan_network:
        ipv4_address: ${ROUTER_IP}

networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
       - subnet: ${SUBNET}
#         ip_range: 192.168.1.23/32
         gateway: ${GATEWAY_IP}


